config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users

  resources :users
  resources :cities
  resources :attendances, only: [:create, :destroy]
  resources :likes
  resources :like_projects


  root 'projects#index'
  resources :projects
  get '/contact/', to: 'pages#contact'

  scope ':by_city' do
    resources :city, only: [:index]

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :participant, class_name: 'User', foreign_key: 'participant_id'
  belongs_to :involved_project, class_name: 'Project', foreign_key: 'involved_project_id'
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :projects

  validates :name, presence: true
  validates :zip_code, 
    presence: true,
    uniqueness: true,
    format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "Veuillez renseigner un code postal français" }

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :project, class_name: 'Project', foreign_key: 'project_id'

  def in_like
    self.projects
  end
  
end

app/models/like_project.rb
class LikeProject < ApplicationRecord
	belongs_to :like, optional:true
	belongs_to :project, optional:true
end

app/models/project.rb
class Project < ApplicationRecord



  belongs_to :city
  belongs_to :architect, class_name: 'User', foreign_key: 'architect_id'
  has_many :attendances, foreign_key: 'involved_project_id'
  has_many :participants, class_name: 'User', through: :attendances, foreign_key: 'participant_id'
  has_many :likes
  has_many :fans, class_name: 'User', through: :likes, foreign_key: 'fan_id'

  validates :title, presence: true, length: { in: 5..140 }
  validates :location, presence: true
  validates :description, presence: true, length: { in: 20..1000 }
  validates :number_of_participants, 
    presence: true,
    numericality: { greater_than_or_equal_to: 0 }
  validates :amount_needed,
    presence: true,
    numericality: { greater_than_or_equal_to: 0 }


scope :by_city, lambda {|city| joins(:city).where('cities.name = ?',city)}




end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :validatable
  belongs_to :city
  has_many :organised_projects, class_name: 'Project'
  has_many :attendances, foreign_key: 'participant_id'
  has_many :involved_projects, class_name: 'Project', through: :attendances, foreign_key: 'involved_project_id'
  has_many :likes
  has_many :favorite_projects, class_name: 'Project', through: :likes, foreign_key: 'favorite_project_id'
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, length: {maximum: 800}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

layout :set_layout

def set_layout
    if current_user
      'profil'
    else
      'application'
    end
 end
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :description, :email, :password, :city_id) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :description, :email, :password, :current_password, :city_id) }
        end

 # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
 

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  
  def create
    @attendance = Attendance.new(involved_project_id: params[:project_id], participant: current_user)
    if @attendance.save
      redirect_to project_path(params[:project_id])
    else
      redirect_to project_path(params[:project_id])
    end
  end

  def destroy
    
  end

end

app/controllers/like_projects_controller.rb
class LikeProjectsController < ApplicationController
before_action :authenticate_user!

  def index 
    @like_projects = LikeProject.all
  end


  def show
  end

  def create 
    @like = Like.find_by(user: current_user)
    @project = Project.find_by(id: params[:project_id])
    @like_project = LikeProject.new(like: @like, project: @project)
      if @like_project.save 

      redirect_to root_path
      flash[:alert] = "Vous avez liké le projet"
      else

      flash[:error] = 'Le projet n\'a pas été liké'
      redirect_to projects_path
      end
  end


  def destroy
    @like = Like.find_by(user: current_user)
    @project = Project.find_by(id: params[:id])
    @like_project = LikeProject.find_by(like: @like, project: @project)
    if @like_project.destroy
      redirect_to like_path(@like.id)
      flash[:alert] = "Vous n'aimez plus le projet"
    else
      flash[:alert] = "Le projet ne fait plus partie de vos projets favoris"
    end
  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
     before_action :authenticate_user!

  def show
    @like = Like.find_by(user: current_user)
      if @like.projects != nil
        @like_projects = LikeProject.all.select {|like_project| like_project.like == @like}
      else 
        redirect_to root_path
        flash[:alert] = "Votre liste de projets favoris est vide"
    end
  end




end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :authenticate_user!, except: [:index]

	has_scope :by_city

	def index
		
	  @projects = apply_scopes(Project).all
	  @cities = City.all
	end

	def show
	  @project = Project.find(params[:id])
	end

	def new
	  @project = Project.new
	end

	def create
	  @project = Project.new(project_params)
	  @project.city = current_user.city
	  @project.architect = current_user
	  if @project.save
	  	redirect_to @project
	  else
	  	render :new
	  end
	end
	
	private

	def project_params
	  params.permit(:title, :description, :location, :number_of_participants, :amount_needed)
	end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!, only: [:show]

  def show


  	@user = User.find(current_user.id)

	if current_user.id != @user.id
	  flash[:alert] = "Vous ne pouvez pas accéder à la page de profil d'un autre utilisateur."
	  redirect_to root_path
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/like_projects_helper.rb
module LikeProjectsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlist_helper.rb
module WishlistHelper
end

app/helpers/wishlist_projects_helper.rb
module WishlistProjectsHelper
end

app/views/like_projects/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
Test
</body>
</html>

app/views/likes/show.html.erb
<!doctype html>
<html lang="zxx">

<head>
  <script src="https://kit.fontawesome.com/ec017e33af.js" crossorigin="anonymous"></script>
</head>

<body>

  <!--================Home Banner Area =================-->
  <!-- breadcrumb start-->
  <section class="breadcrumb breadcrumb_bg">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="breadcrumb_iner">
            <div class="breadcrumb_iner_item">
              <h2>Mes projets favoris</h2>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- breadcrumb start-->

  <!--================Cart Area =================-->
  <section class="cart_area padding_top">
    <div class="container">
      <div class="cart_inner">
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <% @like.in_like.each do |like| %>
              <tr>
                <td>
                  <div class="media">
                    <div class="d-flex">
                      <img src="img/product/single-product/cart-1.jpg" alt="" />
                    </div>
                    <div class="media-body">
                      <p><%= @project %></p>
                    </div>
                  </div>
                </td>
                <td>
                </td>
                <td>
                  <div class="cupon_text float-right">
                    <%= button_to "Participer au projet", attendances_path, data: { confirm: "Voulez-vous rejoindre le projet ? Un email avec les coordonnées de l'organisateur vous sera alors envoyé." , disable_with: 'Déjà rejoint' }, params: { project_id: @project.id }, class: "btn_1" %>
                  </div>
                </td>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
  </section>
  <!--================End Cart Area =================-->

  <!--::footer_part start::-->
  <footer class="footer_part">
    <div class="container">
      <div class="row justify-content-around">
        <div class="col-sm-6 col-lg-2">
          <div class="single_footer_part">
            <h4>Top Products</h4>
            <ul class="list-unstyled">
              <li><a href="">Managed Website</a></li>
              <li><a href="">Manage Reputation</a></li>
              <li><a href="">Power Tools</a></li>
              <li><a href="">Marketing Service</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6 col-lg-2">
          <div class="single_footer_part">
            <h4>Quick Links</h4>
            <ul class="list-unstyled">
              <li><a href="">Jobs</a></li>
              <li><a href="">Brand Assets</a></li>
              <li><a href="">Investor Relations</a></li>
              <li><a href="">Terms of Service</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6 col-lg-2">
          <div class="single_footer_part">
            <h4>Features</h4>
            <ul class="list-unstyled">
              <li><a href="">Jobs</a></li>
              <li><a href="">Brand Assets</a></li>
              <li><a href="">Investor Relations</a></li>
              <li><a href="">Terms of Service</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6 col-lg-2">
          <div class="single_footer_part">
            <h4>Resources</h4>
            <ul class="list-unstyled">
              <li><a href="">Guides</a></li>
              <li><a href="">Research</a></li>
              <li><a href="">Experts</a></li>
              <li><a href="">Agencies</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6 col-lg-4">
          <div class="single_footer_part">
            <h4>Newsletter</h4>
            <p>Heaven fruitful doesn't over lesser in days. Appear creeping
            </p>
            <div id="mc_embed_signup">
              <form target="_blank"
                action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                method="get" class="subscribe_form relative mail_part">
                <input type="email" name="email" id="newsletter-form-email" placeholder="Email Address"
                  class="placeholder hide-on-focus" onfocus="this.placeholder = ''"
                  onblur="this.placeholder = ' Email Address '">
                <button type="submit" name="submit" id="newsletter-submit"
                  class="email_icon newsletter-submit button-contactForm">subscribe</button>
                <div class="mt-10 info"></div>
              </form>
            </div>
          </div>
        </div>
      </div>

    </div>
    <div class="copyright_part">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="copyright_text">
              <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></P>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="footer_icon social_icon">
              <ul class="list-unstyled">
                <li><a href="#" class="single_social_icon"><i class="fab fa-facebook-f"></i></a></li>
                <li><a href="#" class="single_social_icon"><i class="fab fa-twitter"></i></a></li>
                <li><a href="#" class="single_social_icon"><i class="fas fa-globe"></i></a></li>
                <li><a href="#" class="single_social_icon"><i class="fab fa-behance"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!--::footer_part end::-->

  <!-- jquery plugins here-->
  <!-- jquery -->
  <script src="js/jquery-1.12.1.min.js"></script>
  <!-- popper js -->
  <script src="js/popper.min.js"></script>
  <!-- bootstrap js -->
  <script src="js/bootstrap.min.js"></script>
  <!-- easing js -->
  <script src="js/jquery.magnific-popup.js"></script>
  <!-- swiper js -->
  <script src="js/swiper.min.js"></script>
  <!-- swiper js -->
  <script src="js/masonry.pkgd.js"></script>
  <!-- particles js -->
  <script src="js/owl.carousel.min.js"></script>
  <script src="js/jquery.nice-select.min.js"></script>
  <!-- slick js -->
  <script src="js/slick.min.js"></script>
  <script src="js/jquery.counterup.min.js"></script>
  <script src="js/waypoints.min.js"></script>
  <script src="js/contact.js"></script>
  <script src="js/jquery.ajaxchimp.min.js"></script>
  <script src="js/jquery.form.js"></script>
  <script src="js/jquery.validate.min.js"></script>
  <script src="js/mail-script.js"></script>
  <script src="js/stellar.js"></script>
  <script src="js/price_rangs.js"></script>
  <!-- custom js -->
  <script src="js/custom.js"></script>
</body>

</html>

app/views/projects/index.html.erb
<head>

</head>

<body>
 

<!-- banner part start-->
<section class="banner_part">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12">
                <div class="banner_slider owl-carousel">
                    <div class="single_banner_slider">
                        <div class="row">
                            <div class="col-lg-5 col-md-8">
                                <div class="banner_text">
                                    <div class="banner_text_iner">
                                        <h1>Le Crowd Funding Entre Voisins </h1>
                                        <p>Découvrez <b><strong>VoisinAct </strong></b>, la première plateforme pour <b><strong> améliorer le quotidien de nos quartiers </strong></b>. Parcours le site et découvre <b>les projets qui t'intéresse le plus </b>, tu pourras les soutenir <b>financièrement</b> ou même apporter <b>un coup de main</b> ! Quoi tu as une idée de projet ? Génial ! <b><strong>Présentes là à la communauté </strong></b> ! </p>
                                        <%= link_to "Lance ton projet", new_project_path,  :class => "btn_2"%>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-7 col-md-4">
                            <div class="banner_img d-none d-lg-block">
                                <%= image_tag('VoisinJumbo.jpg') %>
                            </div>
                        </div>

                        </div>
                    </div>
                </div>
                <div class="slider-counter"></div>
            </div>
        </div>
    </div>
</section>
<!-- banner part start-->

    <!-- Les projets en cours-->
    <section class="feature_part padding_top">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="section_tittle text-center">
                        <h2><b>Les Projets En Cours</b></h2> <br><hr><p> Trier par ville </p>
                        <%= link_to "Toutes", root_path,  :class => "btn_3"%>
                        <% @cities.each do |city| %>
                        <%= link_to city.name, root_path(by_city: city.name),  :class => "btn_3"%>
                        <%end%>

                        <hr>
                    </div>

                </div>
            </div>
            <div class="row align-items-center justify-content-between">
                <% @projects.each do |project| %>
                <div class="col-lg-4 col-sm-4">
                    <div class="single_feature_post_text">
                        <p><b> <%= project.city.name %></b></p>
                        <h3><b><strong><%= project.title %></strong></b></h3>
                        <p><b> <%= project.number_of_participants %> participants</b></p>
                        <%= link_to "Plus d'informations", project_path(project.id), :class => 'feature_btn'%>
  
                        <img src="img/feature/feature_1.png" alt="">
                        <br><h4><b>Objectif à atteindre <strong><%= project.amount_needed %> $</strong></b></h4>
                    </div>
                </div>
                <%end%>
            </div>
        </div>
    </section>
    <!-- Les projets en cours-->



    <!-- Projet du Mois-->
    <section class="our_offer section_padding">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-lg-6 col-md-6">
                    <div class="offer_img">
                        <img src="img/offer_img.png" alt="">
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="offer_text">
                        <h2>Le Super
                            Projet du Mois !</h2>
                       
                     </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- awesome_shop part start-->

    
</body>

</html>

app/views/projects/new.html.erb
  <head>
   
 </head>

<body>

<!-- banner part start-->
<section class="banner_part">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12">
                <div class="banner_slider owl-carousel">
                    <div class="single_banner_slider" style="max-height: 100px">
                        <div class="row">
                            <div class="col-lg-12 col-md-12">
                                <div class="banner_text">
                                    <div class="banner_text_iner">
                                        
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="slider-counter"></div>
            </div>
        </div>
    </div>
</section>
<!-- banner part start-->

<section class="login_part padding_top">
    <div class="container">
      <div class="col-lg-12 col-md-12">
        <div class="login_part_form col-lg-12 col-md-12">
          <div class="login_part_form_iner">
            <h3>Lance ton projet sur VoisinAct dès Maintenant !
                <p>Veuillez s'il vous plaît décrire votre projet dans le formulaire ci-dessous</p>
            </h3>

              <%=form_tag url_for(action: 'create'), method: 'post' do %> 
              <%= text_field_tag 'title' ,"", class:"form-control", placeholder: "Titre" %>
              <br/>
              <%= text_field_tag 'location' ,"", class:"form-control", placeholder: "Lieu" %><br/>
              <br/>
              <%= text_area_tag 'description' ,"", class:"form-control", placeholder: "Description" %><br/>
              <%= number_field_tag 'number_of_participants' ,"", class:"form-control", placeholder: "Nombre de personnes supplémentaires requise pour la bonne conduite du projet" %><br/>
              <%= number_field_tag 'amount_needed' ,"", class:"form-control", placeholder: "Budget souhaité pour votre projet" %><br/>
              <%= submit_tag "Créer", class: 'btn_2' %>
            <% end %>

          </div>
        </div>
      </div>
    </div>
</section>


</body>


   


 </html>

app/views/projects/show.html.erb
<head>
  <script src="https://kit.fontawesome.com/ec017e33af.js" crossorigin="anonymous"></script>
</head>
<body>
<!-- banner part start-->
<section class="banner_part">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12">
                <div class="banner_slider owl-carousel">
                    <div class="single_banner_slider" style="max-height: 100px">
                        <div class="row">
                            <div class="col-lg-12 col-md-12">
                                <div class="banner_text">
                                    <div class="banner_text_iner">
                                        
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="slider-counter"></div>
            </div>
        </div>
    </div>
</section>
<!-- banner part start-->

  <!--================Single Product Area =================-->
  <div class="product_image_area section_padding">
    <div class="container">
      <div class="row s_product_inner justify-content-between">
        <div class="col-lg-7 col-xl-7">
          <div class="product_slider_img">
            <div id="vertical">
              <div data-thumb="img/product/single-product/product_1.png">
                <img src="img/product/single-product/product_1.png" />
              </div>
              <div data-thumb="img/product/single-product/product_1.png">
                <img src="img/product/single-product/product_1.png" />
              </div>
              <div data-thumb="img/product/single-product/product_1.png">
                <img src="img/product/single-product/product_1.png" />
              </div>
              <div data-thumb="img/product/single-product/product_1.png">
                <img src="img/product/single-product/product_1.png" />
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-5 col-xl-4">
          <div class="s_product_text">
            <h5>previous <span>|</span> next</h5>
            <h3><%= @project.title %></h3>
            <ul class="list">
              <li>
                  <p>Type d'action : <b> Ecologique </b></p> 
              </li>
            </ul>
            <ul>
              <li>                                                          
                <p> <h4> Ressources Requises</h4> Besoins Humains : <b> <%= @project.number_of_participants %> personnes </b> <br> Besoins financier : <b> <%= @project.amount_needed %> $ </b></p>
              </li>
              <li>  
                <p> <%= @project.description %> </p>
                <p> https://www.leetchi.com/fr/c/lW3bmkQl </p>
              </li>
            </ul>
            <% if current_user != @project.architect %>
              <div class="card_area d-flex justify-content-between align-items-center">
                <% if @project.number_of_participants <= @project.attendances.length %>
                  <p>Le nombre de participants maximum a été atteint.</p>
                <% elsif @project.participants.include?(current_user) %>
                  <p>Vous participez déjà à ce projet !</p>
                <% else %>
                  <%= button_to "Participer au projet", attendances_path, data: { confirm: "Voulez-vous rejoindre le projet ? Un email avec les coordonnées de l'organisateur vous sera alors envoyé." , disable_with: 'Déjà rejoint' }, params: { project_id: @project.id }, class: "btn_3" %>
                <% end %>
                <div class="like_us"> <i class="fas fa-heart"></i> 
                  <%= link_to "Like", like_projects_path(project_id:@project.id), method: :post, :class=> 'btn btn-outline-danger' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--================End Single Product Area =================-->

  <!--================Product Description Area =================-->
  <section class="product_description_area">
    <div class="container">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home"
            aria-selected="true">Description</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile"
            aria-selected="false">Specification</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact"
            aria-selected="false">Questions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" id="review-tab" data-toggle="tab" href="#review" role="tab" aria-controls="review"
            aria-selected="false">Personnes ayant rejoins le projet</a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade" id="home" role="tabpanel" aria-labelledby="home-tab">
          <p>
            Description du projet
          </p>
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
          <div class="table-responsive">
            <table class="table">
              <tbody>
                <tr>
                  <td>
                    <h5>Date de début</h5>
                  </td>
                  <td>
                    <h5>25/03/12</h5>
                  </td>
                </tr>
                <tr>
                  <td>
                    <h5>Date de fin</h5>
                  </td>
                  <td>
                    <h5>26/03/12</h5>
                  </td>
                </tr>
                <tr>
                  <td>
                    <h5>Côut financiers</h5>
                  </td>
                  <td>
                    <h5>1000 euros</h5>
                  </td>
                </tr>
                <tr>
                  <td>
                    <h5>Nombre de personnes requises</h5>
                  </td>
                  <td>
                    <h5>10gm</h5>
                  </td>
                </tr>
                <tr>
                  <td>
                    <h5>Ville</h5>
                  </td>
                  <td>
                    <h5>Paris</h5>
                  </td>
                </tr>
                <tr>
                  <td>
                    <h5>Temps demandé</h5>
                  </td>
                  <td>
                    <h5>2h par jour</h5>
                  </td>
                </tr>
                <tr>
                  <td>
                    <h5>Profil recherché</h5>
                  </td>
                  <td>
                    <h5>Ingénieur</h5>
                  </td>
                </tr>
                <tr>
                  <td>
                    <h5>Autorisation de la mairie requise</h5>
                  </td>
                  <td>
                    <h5>non</h5>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--================End Product Description Area =================-->

  <!-- product_list part start-->
  <section class="product_list best_seller">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-12">
          <div class="section_tittle text-center">
            <h2>Projets similaires </h2>
          </div>
        </div>
      </div>
      <div class="row align-items-center justify-content-between">
        <div class="col-lg-12">
          <div class="best_product_slider owl-carousel">
            <div class="single_product_item">
              <img src="img/product/product_1.png" alt="">
              <div class="single_product_text">
                <h4>Quartz Belt Watch</h4>
                <h3>$150.00</h3>
              </div>
            </div>
            <div class="single_product_item">
              <img src="img/product/product_2.png" alt="">
              <div class="single_product_text">
                <h4>Quartz Belt Watch</h4>
                <h3>$150.00</h3>
              </div>
            </div>
            <div class="single_product_item">
              <img src="img/product/product_3.png" alt="">
              <div class="single_product_text">
                <h4>Quartz Belt Watch</h4>
                <h3>$150.00</h3>
              </div>
            </div>
            <div class="single_product_item">
              <img src="img/product/product_4.png" alt="">
              <div class="single_product_text">
                <h4>Quartz Belt Watch</h4>
                <h3>$150.00</h3>
              </div>
            </div>
            <div class="single_product_item">
              <img src="img/product/product_5.png" alt="">
              <div class="single_product_text">
                <h4>Quartz Belt Watch</h4>
                <h3>$150.00</h3>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- product_list part end-->


</body>